version: '3'
services:
  protoc:
    build: .
    platform: linux/x86_64
    volumes:
      - ./:/repo
    working_dir: /repo
    command: --include_imports --descriptor_set_out=/repo/fds.pb --go_out=/repo --go_opt=paths=source_relative example.proto
